"""StockToday read-only catalogue, retrieved 2026-09-22.
Sources: stocktoday.cn/api/tools/methods and ClawHub stocktoday API reference.
Catalogue presence does not establish account entitlement or data quality.
"""

from .stocktoday_inventory import INVENTORY_PATH, method_map

API_PARAMS = {
    'adj_factor': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'anns_d': frozenset(['ann_date', 'end_date', 'start_date', 'ts_code']),
    'bak_basic': frozenset(['trade_date', 'ts_code']),
    'bak_daily': frozenset(['end_date', 'limit', 'offset', 'start_date', 'trade_date', 'ts_code']),
    'balancesheet': frozenset(['ann_date', 'comp_type', 'end_date', 'period', 'report_type', 'start_date', 'ts_code']),
    'balancesheet_vip': frozenset(['ann_date', 'comp_type', 'end_date', 'period', 'report_type', 'start_date', 'ts_code']),
    'bc_bestotcqt': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'bc_otcqt': frozenset(['bank', 'end_date', 'start_date', 'trade_date', 'ts_code']),
    'block_trade': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'bo_cinema': frozenset(['date']),
    'bo_daily': frozenset(['date']),
    'bo_monthly': frozenset(['date']),
    'bo_weekly': frozenset(['date']),
    'bond_blk': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'bond_blk_detail': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'broker_recommend': frozenset(['month']),
    'bse_mapping': frozenset(['n_code', 'o_code', 'ts_code']),
    'cashflow': frozenset(['ann_date', 'comp_type', 'end_date', 'f_ann_date', 'is_calc', 'period', 'report_type', 'start_date', 'ts_code']),
    'cashflow_vip': frozenset(['ann_date', 'comp_type', 'end_date', 'period', 'report_type', 'start_date', 'ts_code']),
    'cb_basic': frozenset(['exchange', 'list_date', 'ts_code']),
    'cb_call': frozenset(['ann_date', 'end_date', 'start_date', 'ts_code']),
    'cb_daily': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'cb_factor_pro': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'cb_issue': frozenset(['ann_date', 'end_date', 'start_date', 'ts_code']),
    'cb_price_chg': frozenset(['ts_code']),
    'cb_rate': frozenset(['ts_code']),
    'cb_share': frozenset(['ann_date', 'end_date', 'start_date', 'ts_code']),
    'ccass_hold': frozenset(['end_date', 'hk_code', 'start_date', 'trade_date', 'ts_code']),
    'ccass_hold_detail': frozenset(['end_date', 'hk_code', 'start_date', 'trade_date', 'ts_code']),
    'cctv_news': frozenset(['date', 'end_date', 'start_date']),
    'ci_daily': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'ci_index_member': frozenset(['index_code', 'is_new', 'l1_code', 'l2_code', 'l3_code', 'ts_code']),
    'cn_cpi': frozenset(['end_m', 'm', 'start_m']),
    'cn_gdp': frozenset(['end_q', 'q', 'start_q']),
    'cn_m': frozenset(['end_date', 'end_m', 'm', 'start_date', 'start_m']),
    'cn_pmi': frozenset(['end_date', 'end_m', 'm', 'start_date', 'start_m']),
    'cn_ppi': frozenset(['end_m', 'm', 'start_m']),
    'cyq_chips': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'cyq_perf': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'daily': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'daily_basic': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'daily_info': frozenset(['end_date', 'exchange', 'start_date', 'trade_date', 'ts_code']),
    'dc_concept': frozenset(['name', 'theme_code', 'trade_date']),
    'dc_concept_cons': frozenset(['theme_code', 'trade_date', 'ts_code']),
    'dc_daily': frozenset(['end_date', 'idx_type', 'start_date', 'trade_date', 'ts_code']),
    'dc_hot': frozenset(['hot_type', 'is_new', 'market', 'trade_date', 'ts_code']),
    'dc_index': frozenset(['end_date', 'idx_type', 'name', 'start_date', 'trade_date', 'ts_code']),
    'dc_member': frozenset(['con_code', 'end_date', 'start_date', 'trade_date', 'ts_code']),
    'disclosure_date': frozenset(['actual_date', 'ann_date', 'end_date', 'period', 'pre_date', 'start_date', 'ts_code']),
    'dividend': frozenset(['ann_date', 'ex_date', 'imp_ann_date', 'record_date', 'ts_code']),
    'eco_cal': frozenset(['country', 'currency', 'date', 'end_date', 'event', 'start_date']),
    'etf_basic': frozenset(['exchange', 'index_code', 'list_date', 'list_status', 'mgr', 'mgr_name', 'ts_code']),
    'etf_index': frozenset(['base_date', 'end_date', 'pub_date', 'start_date', 'ts_code']),
    'etf_mins': frozenset(['end_date', 'freq', 'start_date', 'trade_date', 'ts_code']),
    'etf_share_size': frozenset(['ts_code']),
    'express': frozenset(['ann_date', 'end_date', 'period', 'start_date', 'ts_code']),
    'express_vip': frozenset(['end_date', 'start_date', 'ts_code']),
    'film_record': frozenset(['ann_date', 'end_date', 'start_date']),
    'fina_audit': frozenset(['ann_date', 'end_date', 'period', 'start_date', 'ts_code']),
    'fina_indicator': frozenset(['ann_date', 'end_date', 'period', 'start_date', 'ts_code']),
    'fina_indicator_vip': frozenset(['ann_date', 'comp_type', 'end_date', 'period', 'report_type', 'start_date', 'ts_code']),
    'fina_mainbz': frozenset(['end_date', 'period', 'start_date', 'ts_code', 'type']),
    'fina_mainbz_vip': frozenset(['end_date', 'start_date', 'ts_code']),
    'forecast': frozenset(['ann_date', 'end_date', 'period', 'start_date', 'ts_code', 'type']),
    'forecast_vip': frozenset(['ann_date', 'end_date', 'period', 'start_date', 'ts_code', 'type']),
    'ft_limit': frozenset(['cont', 'end_date', 'exchange', 'start_date', 'trade_date', 'ts_code']),
    'ft_mins': frozenset(['end_date', 'freq', 'start_date', 'ts_code']),
    'fund_adj': frozenset(['end_date', 'limit', 'offset', 'start_date', 'trade_date', 'ts_code']),
    'fund_basic': frozenset(['market', 'status', 'ts_code']),
    'fund_company': frozenset([]),
    'fund_daily': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'fund_div': frozenset(['ann_date', 'ex_date', 'pay_date', 'ts_code']),
    'fund_factor_pro': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'fund_manager': frozenset(['ann_date', 'limit', 'name', 'offset', 'ts_code']),
    'fund_nav': frozenset(['end_date', 'market', 'nav_date', 'start_date', 'ts_code']),
    'fund_portfolio': frozenset(['ann_date', 'end_date', 'period', 'start_date', 'symbol', 'ts_code']),
    'fund_sales_ratio': frozenset(['year']),
    'fund_sales_vol': frozenset(['name', 'quarter', 'year']),
    'fund_share': frozenset(['end_date', 'market', 'start_date', 'trade_date', 'ts_code']),
    'fut_basic': frozenset(['exchange', 'fut_code', 'fut_type', 'list_date', 'ts_code']),
    'fut_daily': frozenset(['end_date', 'exchange', 'start_date', 'trade_date', 'ts_code']),
    'fut_holding': frozenset(['end_date', 'exchange', 'start_date', 'symbol', 'trade_date']),
    'fut_mapping': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'fut_settle': frozenset(['end_date', 'exchange', 'start_date', 'trade_date', 'ts_code']),
    'fut_weekly_detail': frozenset(['end_week', 'exchange', 'prd', 'start_week', 'week']),
    'fut_weekly_monthly': frozenset(['end_date', 'exchange', 'freq', 'start_date', 'trade_date', 'ts_code']),
    'fut_wsr': frozenset(['end_date', 'exchange', 'start_date', 'symbol', 'trade_date']),
    'fx_daily': frozenset(['end_date', 'exchange', 'start_date', 'trade_date', 'ts_code']),
    'fx_obasic': frozenset(['classify', 'exchange', 'ts_code']),
    'ggt_daily': frozenset(['end_date', 'start_date', 'trade_date']),
    'ggt_monthly': frozenset(['end_date', 'end_month', 'month', 'start_date', 'start_month', 'trade_date']),
    'ggt_top10': frozenset(['end_date', 'market_type', 'start_date', 'trade_date', 'ts_code']),
    'gz_index': frozenset(['date', 'end_date', 'start_date', 'trade_date', 'ts_code']),
    'hibor': frozenset(['date', 'end_date', 'start_date']),
    'hk_adjfactor': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'hk_balancesheet': frozenset(['end_date', 'ind_name', 'period', 'start_date', 'ts_code']),
    'hk_basic': frozenset(['list_status', 'trade_date', 'ts_code']),
    'hk_cashflow': frozenset(['end_date', 'ind_name', 'period', 'start_date', 'ts_code']),
    'hk_daily': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'hk_daily_adj': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'hk_fina_indicator': frozenset(['end_date', 'period', 'report_type', 'start_date', 'ts_code']),
    'hk_hold': frozenset(['code', 'end_date', 'exchange', 'start_date', 'trade_date', 'ts_code']),
    'hk_income': frozenset(['end_date', 'ind_name', 'period', 'start_date', 'ts_code']),
    'hk_mins': frozenset(['end_date', 'freq', 'start_date', 'ts_code']),
    'hk_tradecal': frozenset(['end_date', 'is_open', 'start_date']),
    'hm_detail': frozenset(['end_date', 'hm_name', 'start_date', 'trade_date', 'ts_code']),
    'hm_list': frozenset(['name']),
    'hsgt_top10': frozenset(['end_date', 'market_type', 'start_date', 'trade_date', 'ts_code']),
    'idx_factor_pro': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'idx_mins': frozenset(['end_date', 'freq', 'start_date', 'trade_date', 'ts_code']),
    'income': frozenset(['ann_date', 'comp_type', 'end_date', 'f_ann_date', 'period', 'report_type', 'start_date', 'ts_code']),
    'income_vip': frozenset(['ann_date', 'comp_type', 'end_date', 'period', 'report_type', 'start_date', 'ts_code']),
    'index_basic': frozenset(['category', 'market', 'name', 'publisher', 'symbol', 'ts_code']),
    'index_classify': frozenset(['index_code', 'level', 'parent_code', 'src']),
    'index_daily': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'index_dailybasic': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'index_global': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'index_member_all': frozenset(['is_new', 'l1_code', 'l2_code', 'l3_code', 'ts_code']),
    'index_monthly': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'index_weekly': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'index_weight': frozenset(['end_date', 'index_code', 'start_date', 'trade_date']),
    'irm_qa_sh': frozenset(['end_date', 'pub_date', 'start_date', 'trade_date', 'ts_code']),
    'irm_qa_sz': frozenset(['end_date', 'pub_date', 'start_date', 'trade_date', 'ts_code']),
    'kpl_concept': frozenset(['trade_date']),
    'kpl_concept_cons': frozenset(['con_code', 'trade_date', 'ts_code']),
    'kpl_list': frozenset(['end_date', 'start_date', 'tag', 'trade_date', 'ts_code']),
    'libor': frozenset(['curr_type', 'date', 'end_date', 'start_date']),
    'limit_cpt_list': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'limit_list_d': frozenset(['end_date', 'exchange', 'limit_type', 'start_date', 'trade_date', 'ts_code']),
    'limit_list_ths': frozenset(['end_date', 'limit_type', 'market', 'start_date', 'trade_date', 'ts_code']),
    'limit_step': frozenset(['end_date', 'nums', 'start_date', 'trade_date', 'ts_code']),
    'major_news': frozenset(['end_date', 'src', 'start_date']),
    'margin': frozenset(['end_date', 'exchange_id', 'start_date', 'trade_date']),
    'margin_detail': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'margin_secs': frozenset(['end_date', 'exchange', 'start_date', 'trade_date', 'ts_code']),
    'moneyflow': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'moneyflow_cnt_ths': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'moneyflow_dc': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'moneyflow_hsgt': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'moneyflow_ind_dc': frozenset(['content_type', 'end_date', 'start_date', 'trade_date', 'ts_code']),
    'moneyflow_ind_ths': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'moneyflow_mkt_dc': frozenset(['end_date', 'start_date', 'trade_date']),
    'moneyflow_ths': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'monthly': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'namechange': frozenset(['end_date', 'start_date', 'ts_code']),
    'new_share': frozenset(['end_date', 'start_date', 'ts_code']),
    'news': frozenset(['end_date', 'src', 'start_date']),
    'npr': frozenset(['end_date', 'org', 'ptype', 'start_date']),
    'opt_basic': frozenset(['call_put', 'exchange', 'list_date', 'opt_code', 'ts_code']),
    'opt_daily': frozenset(['end_date', 'exchange', 'start_date', 'trade_date', 'ts_code']),
    'opt_mins': frozenset(['end_date', 'freq', 'start_date', 'trade_date', 'ts_code']),
    'pledge_detail': frozenset(['ts_code']),
    'pledge_stat': frozenset(['end_date', 'ts_code']),
    'pro_bar': frozenset(['adj', 'adjfactor', 'asset', 'end_date', 'factors', 'freq', 'ma', 'start_date', 'ts_code']),
    'realtime_list': frozenset([]),
    'realtime_quote': frozenset(['ts_code']),
    'realtime_tick': frozenset(['ts_code']),
    'repo_daily': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'report_rc': frozenset(['end_date', 'report_date', 'start_date', 'ts_code']),
    'repurchase': frozenset(['ann_date', 'end_date', 'start_date', 'ts_code']),
    'research_report': frozenset(['end_date', 'ind_name', 'inst_csname', 'report_type', 'start_date', 'trade_date', 'ts_code']),
    'rt_etf_k': frozenset(['topic', 'ts_code']),
    'rt_etf_min': frozenset(['freq', 'ts_code']),
    'rt_etf_tick': frozenset(['topic', 'ts_code']),
    'rt_fut_min': frozenset(['freq', 'ts_code']),
    'rt_hk_k': frozenset(['ts_code']),
    'rt_hk_tick': frozenset(['ts_code']),
    'rt_idx_k': frozenset(['ts_code']),
    'rt_idx_min': frozenset(['freq', 'ts_code']),
    'rt_idx_tick': frozenset(['ts_code']),
    'rt_k': frozenset(['ts_code']),
    'rt_min': frozenset(['freq', 'ts_code']),
    'rt_sw_k': frozenset(['ts_code']),
    'rt_sw_tick': frozenset(['ts_code']),
    'rt_tick': frozenset(['ts_code']),
    'sf_month': frozenset(['end_m', 'm', 'start_m']),
    'sge_basic': frozenset(['ts_code']),
    'sge_daily': frozenset(['end_date', 'prd', 'start_date', 'trade_date', 'ts_code']),
    'share_float': frozenset(['ann_date', 'end_date', 'float_date', 'start_date', 'ts_code']),
    'shibor': frozenset(['date', 'end_date', 'start_date']),
    'shibor_lpr': frozenset(['date', 'end_date', 'start_date']),
    'shibor_quote': frozenset(['bank', 'date', 'end_date', 'start_date']),
    'slb_len': frozenset(['end_date', 'start_date', 'trade_date']),
    'slb_len_mm': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'slb_sec': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'slb_sec_detail': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'st': frozenset(['imp_date', 'pub_date', 'ts_code']),
    'stk_account': frozenset(['date', 'end_date', 'start_date']),
    'stk_account_old': frozenset(['end_date', 'start_date']),
    'stk_ah_comparison': frozenset(['end_date', 'hk_code', 'start_date', 'trade_date', 'ts_code']),
    'stk_auction': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'stk_auction_c': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'stk_auction_o': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'stk_factor_pro': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'stk_holdernumber': frozenset(['ann_date', 'end_date', 'enddate', 'start_date', 'ts_code']),
    'stk_holdertrade': frozenset(['ann_date', 'end_date', 'holder_type', 'start_date', 'trade_type', 'ts_code']),
    'stk_limit': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'stk_managers': frozenset(['ann_date', 'end_date', 'start_date', 'ts_code']),
    'stk_mins': frozenset(['end_date', 'freq', 'start_date', 'trade_date', 'ts_code']),
    'stk_nineturn': frozenset(['end_date', 'freq', 'start_date', 'trade_date', 'ts_code']),
    'stk_premarket': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'stk_rewards': frozenset(['end_date', 'ts_code']),
    'stk_surv': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'stk_week_month_adj': frozenset(['end_date', 'freq', 'start_date', 'trade_date', 'ts_code']),
    'stk_weekly_monthly': frozenset(['end_date', 'freq', 'start_date', 'trade_date', 'ts_code']),
    'stock_basic': frozenset(['exchange', 'is_hs', 'list_status', 'market', 'ts_code']),
    'stock_company': frozenset(['exchange', 'ts_code']),
    'stock_hsgt': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code', 'type']),
    'stock_st': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'suspend_d': frozenset(['end_date', 'start_date', 'suspend_type', 'trade_date', 'ts_code']),
    'sw_daily': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'sz_daily_info': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'tdx_daily': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'tdx_index': frozenset(['idx_type', 'trade_date', 'ts_code']),
    'tdx_member': frozenset(['con_code', 'end_date', 'start_date', 'trade_date', 'ts_code']),
    'teleplay_record': frozenset(['end_date', 'org', 'report_date', 'start_date']),
    'ths_daily': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'ths_hot': frozenset(['is_new', 'market', 'trade_date', 'ts_code']),
    'ths_index': frozenset(['exchange', 'name', 'ts_code', 'type']),
    'ths_member': frozenset(['con_code', 'end_date', 'is_new', 'start_date', 'ts_code']),
    'ths_news': frozenset(['end_date', 'limit', 'start_date', 'trade_date']),
    'tmt_twincome': frozenset(['date', 'end_date', 'item', 'start_date']),
    'tmt_twincomedetail': frozenset(['date', 'end_date', 'item', 'source', 'start_date', 'symbol']),
    'top10_floatholders': frozenset(['ann_date', 'end_date', 'period', 'start_date', 'ts_code']),
    'top10_holders': frozenset(['ann_date', 'end_date', 'period', 'start_date', 'ts_code']),
    'top_inst': frozenset(['trade_date', 'ts_code']),
    'top_list': frozenset(['trade_date', 'ts_code']),
    'trade_cal': frozenset(['end_date', 'exchange', 'is_open', 'start_date']),
    'us_adjfactor': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'us_balancesheet': frozenset(['end_date', 'ind_name', 'period', 'report_type', 'start_date', 'ts_code']),
    'us_basic': frozenset(['classify', 'limit', 'offset', 'ts_code']),
    'us_cashflow': frozenset(['end_date', 'ind_name', 'period', 'report_type', 'start_date', 'ts_code']),
    'us_daily': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'us_daily_adj': frozenset(['end_date', 'exchange', 'limit', 'offset', 'start_date', 'trade_date', 'ts_code']),
    'us_fina_indicator': frozenset(['end_date', 'period', 'report_type', 'start_date', 'ts_code']),
    'us_income': frozenset(['end_date', 'ind_name', 'period', 'report_type', 'start_date', 'ts_code']),
    'us_tbr': frozenset(['date', 'end_date', 'start_date']),
    'us_tltr': frozenset(['date', 'end_date', 'start_date']),
    'us_tradecal': frozenset(['end_date', 'is_open', 'start_date']),
    'us_trltr': frozenset(['date', 'end_date', 'start_date']),
    'us_trycr': frozenset(['date', 'end_date', 'start_date']),
    'us_tycr': frozenset(['date', 'end_date', 'start_date']),
    'weekly': frozenset(['end_date', 'start_date', 'trade_date', 'ts_code']),
    'wz_index': frozenset(['date', 'end_date', 'start_date', 'trade_date', 'ts_code']),
    'yc_cb': frozenset(['curve_term', 'curve_type', 'end_date', 'start_date', 'trade_date', 'ts_code']),
}


_INVENTORY_METHODS = method_map()
if set(API_PARAMS) != set(_INVENTORY_METHODS):
    raise RuntimeError("StockToday API_PARAMS method names must match the frozen inventory")


PARAMETER_AUDIT = {}
for _name, _method in _INVENTORY_METHODS.items():
    _web_params = frozenset(parameter["name"] for parameter in _method["params"])
    _endpoint_params = frozenset(
        parameter["name"]
        for parameter in _method["params"]
        if parameter["name"] != "fields"
    )
    _catalog_params = API_PARAMS[_name]
    if not _endpoint_params <= _catalog_params:
        raise RuntimeError(
            f"StockToday API_PARAMS is missing endpoint parameters for {_name}"
        )
    PARAMETER_AUDIT[_name] = {
        "web_params": tuple(sorted(_web_params)),
        "endpoint_params": tuple(sorted(_endpoint_params)),
        "catalog_params": tuple(sorted(_catalog_params)),
        "web_only": tuple(sorted(_web_params - _catalog_params)),
        "endpoint_only": tuple(sorted(_endpoint_params - _catalog_params)),
        "catalog_only": tuple(sorted(_catalog_params - _endpoint_params)),
        "fields_documented": "fields" in _web_params,
    }


PARAMETER_AUDIT_SUMMARY = {
    "method_count": len(PARAMETER_AUDIT),
    "methods_with_any_difference": sum(
        bool(item["web_only"] or item["catalog_only"])
        for item in PARAMETER_AUDIT.values()
    ),
    "methods_with_documented_fields": sum(
        item["fields_documented"] for item in PARAMETER_AUDIT.values()
    ),
    "web_only_non_fields": sum(
        any(parameter != "fields" for parameter in item["web_only"])
        for item in PARAMETER_AUDIT.values()
    ),
    "catalog_only_parameter_count": sum(
        len(item["catalog_only"]) for item in PARAMETER_AUDIT.values()
    ),
}
